name: Hello world pipeline for PyQt app

on:
  push:
    tags:
      - 'v*'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout stage
        uses: actions/checkout@v4

      - name: Setup Python stage
        uses: actions/setup-python@v4

      - name: Install dependencies stage
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with PyInstaller stage
        run: |
          pyinstaller --onefile hello.py

      - name: Upload executable as artifact stage
        uses: actions/upload-artifact@v4
        with:
          name: PyQtHelloWorld
          path: dist/hello

      - name: Create GitHub Release stage
        id: create_release  
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: false

      - name: Upload release asset stage
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/hello
          asset_name: hello_asset
          asset_content_type: application/octet-stream
