name: Hello world pipeline for PyQt

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                
            -   name: Setup Pyhton
                uses: actions/setup-python@v4 

            -   name: Install dependencies
                run: | 
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt
            
            -   name: Build with PyInstaller
                run: |
                    pyinstaller --onefile hello.py

            -   name: Upload executable as artifact
                uses: actions/upload-artifact@v4
                with:
                    name: PyQtHelloWorld
                    path: dist/hello
            
            -   name: Create GitHub Release
                uses: ncipollo/release-action@v1
                with:
                    artifacts: "dist/hello"
                    tag: v${{ github.run_number }}